-- V2: transfers and ledger
-- Tables: TRANSFERS, LEDGER_ENTRIES
-- Legal state transitions are enforced in application code and tests, not here.
-- The cross-row "entries balance" invariant is checked by the posting service and
-- by reconciliation; it is deliberately not a database constraint.

CREATE TABLE TRANSFERS (
    TRANSFER_ID             RAW(16)                  NOT NULL,
    SOURCE_ACCOUNT_ID       RAW(16)                  NOT NULL,
    DESTINATION_ACCOUNT_ID  RAW(16)                  NOT NULL,
    AMOUNT                  NUMBER(19,4)             NOT NULL,
    CURRENCY                VARCHAR2(3)              NOT NULL,
    STATUS                  VARCHAR2(20)             NOT NULL,
    REFERENCE               VARCHAR2(140 CHAR),
    CREATED_BY_USER_ID      RAW(16)                  NOT NULL,
    REVERSAL_OF             RAW(16),
    CREATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TRANSFERS          PRIMARY KEY (TRANSFER_ID),
    CONSTRAINT FK_TRANSFERS_SRC      FOREIGN KEY (SOURCE_ACCOUNT_ID)      REFERENCES ACCOUNTS (ACCOUNT_ID),
    CONSTRAINT FK_TRANSFERS_DST      FOREIGN KEY (DESTINATION_ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
    CONSTRAINT FK_TRANSFERS_CREATOR  FOREIGN KEY (CREATED_BY_USER_ID)     REFERENCES APP_USERS (USER_ID),
    CONSTRAINT FK_TRANSFERS_REVERSAL FOREIGN KEY (REVERSAL_OF)            REFERENCES TRANSFERS (TRANSFER_ID),
    -- A transfer is reversed at most once. Also serves as the FK index.
    CONSTRAINT UK_TRANSFERS_REVERSAL UNIQUE (REVERSAL_OF),
    CONSTRAINT CK_TRANSFERS_AMOUNT   CHECK (AMOUNT > 0),
    CONSTRAINT CK_TRANSFERS_CURRENCY CHECK (CURRENCY IN ('USD')),
    CONSTRAINT CK_TRANSFERS_STATUS   CHECK (STATUS IN (
        'RECEIVED', 'VALIDATING', 'PENDING_REVIEW', 'PROCESSING',
        'COMPLETED', 'REJECTED', 'FAILED', 'CANCELLED')),
    CONSTRAINT CK_TRANSFERS_DISTINCT CHECK (SOURCE_ACCOUNT_ID <> DESTINATION_ACCOUNT_ID),
    CONSTRAINT CK_TRANSFERS_NOT_SELF_REV CHECK (REVERSAL_OF IS NULL OR REVERSAL_OF <> TRANSFER_ID)
);

-- Append-only: the runtime principal is granted SELECT and INSERT only.
CREATE TABLE LEDGER_ENTRIES (
    ENTRY_ID        RAW(16)                  NOT NULL,
    TRANSFER_ID     RAW(16)                  NOT NULL,
    ACCOUNT_ID      RAW(16)                  NOT NULL,
    SIDE            VARCHAR2(6)              NOT NULL,
    AMOUNT          NUMBER(19,4)             NOT NULL,
    ENTRY_POSITION  NUMBER(3)                NOT NULL,
    BALANCE_AFTER   NUMBER(19,4)             NOT NULL,
    POSTED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_LEDGER_ENTRIES     PRIMARY KEY (ENTRY_ID),
    CONSTRAINT FK_LEDGER_TRANSFER    FOREIGN KEY (TRANSFER_ID) REFERENCES TRANSFERS (TRANSFER_ID),
    CONSTRAINT FK_LEDGER_ACCOUNT     FOREIGN KEY (ACCOUNT_ID)  REFERENCES ACCOUNTS (ACCOUNT_ID),
    -- Leading column TRANSFER_ID makes a separate transfer_id index redundant.
    CONSTRAINT UK_LEDGER_POSITION    UNIQUE (TRANSFER_ID, ENTRY_POSITION),
    CONSTRAINT CK_LEDGER_SIDE        CHECK (SIDE IN ('DEBIT', 'CREDIT')),
    CONSTRAINT CK_LEDGER_AMOUNT      CHECK (AMOUNT > 0),
    CONSTRAINT CK_LEDGER_POSITION    CHECK (ENTRY_POSITION >= 1),
    CONSTRAINT CK_LEDGER_BAL_AFTER   CHECK (BALANCE_AFTER >= 0)
);
