-- V5: outbox and reconciliation
-- Tables: OUTBOX_EVENTS, RECONCILIATION_RECORDS
-- Kafka publication is tracked here, never on the transfer's state.

-- Delivery is at-least-once. EVENT_ID is the consumers' deduplication key.
CREATE TABLE OUTBOX_EVENTS (
    EVENT_ID         RAW(16)                  NOT NULL,
    TRANSFER_ID      RAW(16)                  NOT NULL,
    EVENT_TYPE       VARCHAR2(50)             NOT NULL,
    PAYLOAD          CLOB                     NOT NULL,
    STATUS           VARCHAR2(12)             NOT NULL,
    ATTEMPTS         NUMBER(5)                DEFAULT 0 NOT NULL,
    CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_ATTEMPT_AT  TIMESTAMP WITH TIME ZONE,
    PUBLISHED_AT     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT PK_OUTBOX_EVENTS     PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_OUTBOX_TRANSFER   FOREIGN KEY (TRANSFER_ID) REFERENCES TRANSFERS (TRANSFER_ID),
    CONSTRAINT CK_OUTBOX_STATUS     CHECK (STATUS IN ('PENDING', 'PUBLISHED', 'FAILED')),
    CONSTRAINT CK_OUTBOX_ATTEMPTS   CHECK (ATTEMPTS >= 0),
    CONSTRAINT CK_OUTBOX_PAYLOAD    CHECK (PAYLOAD IS JSON)
);

-- Independent check of the ledger against transfers. One row per transfer per run.
CREATE TABLE RECONCILIATION_RECORDS (
    ID               RAW(16)                  NOT NULL,
    RUN_ID           RAW(16)                  NOT NULL,
    TRANSFER_ID      RAW(16)                  NOT NULL,
    EXPECTED_AMOUNT  NUMBER(19,4)             NOT NULL,
    ACTUAL_AMOUNT    NUMBER(19,4),
    STATUS           VARCHAR2(12)             NOT NULL,
    RUN_AT           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_RECONCILIATION_RECORDS PRIMARY KEY (ID),
    CONSTRAINT FK_RECON_TRANSFER         FOREIGN KEY (TRANSFER_ID) REFERENCES TRANSFERS (TRANSFER_ID),
    CONSTRAINT UK_RECON_RUN_TRANSFER     UNIQUE (RUN_ID, TRANSFER_ID),
    CONSTRAINT CK_RECON_STATUS           CHECK (STATUS IN ('MATCHED', 'MISMATCHED', 'MISSING'))
);
